ru:
  greeting_message: "Привет! Это Remotely Job Bot. 

Раз в сутки я высылаю самые лучшие вакансии на удаленку. 

Я собираю вакансиию от луших IT компаний из Европы/США/СНГ

Выбери категорию вакансий с помощью кнопок ниже. 

В этом боте нет рекламы, а оповещения редкие и нужные."

  # greeting_message_1: "Я Котик - рекрутинговый бот"
  # greeting_message_2: "Хочу помочь тебе найти работу в IT в втоем городе, удаленно или на релокейт"
  # greeting_message_3: https://meetfrank.com/images/hello/family-guy.gif
  # greeting_message_4: "Я буду доставлять тебе инетересные персонализированные предложениия от разных компаний"
  # greeting_message_5: "Если тебя заинтересут вакансия просто откликнешься на нее"
  # greeting_message_6: "Весь процесс полностью анонимный"
  # greeting_message_7: "Начнем"

  greeting_message_yes: /yes
  greeting_message_3: https://meetfrank.com/images/hello/family-guy.gif
  starting_message: "Хорошо, давай создадим твой профайл, всего пара вопросов"
  starting_profile_email: "Твой email"
  starting_profile_current_position: "Ваша текущая позиция"
  starting_profile_description: "Пару слов про себя"

  starting_profile_thanks: "Спаибо! раз в день я буду присылать тебе нвоые позиции" 


  recruter_message_1: "Привет, Я Bot - рекрутинговый бот. Помогу тебе хантить лучших специалистов в IT"
  recruter_message_2: https://lwlies.com/wp-content/uploads/2017/07/leon-the-professional-1108x0-c-default.jpg
  recruter_message_3: "В моей базее более 1000+ новых талантов каждый месяц"
  recruter_message_4: "Звучит отлтично? Жми /yes"
  recruter_message_5: "Ok. Для начала заполни профайл на сайте"
  recruter_message_6: http://www.smoozy.io/

en:
  greeting_message: "Hi! There"
  greeting_message_1: "I am Smoozy and I will be your guide"
  greeting_message_2: "I am going to show you the <b> undercover </b> job market"
  greeting_message_3: https://meetfrank.com/images/hello/family-guy.gif
  greeting_message_4: "I will bring you direct offers from TOP it company"
  greeting_message_5: "If you interesting you can talk to there"
  greeting_message_6: "You will remain anonymous the whole time"
  greeting_message_7: "Sounds good? (answer yes)"
  greeting_message_yes: /yes
  starting_message: "Ok. Lets go to create your profile in 30 seconds"
  starting_profile: "What is your name?"

  new_vatation: "
    Hi there. I have find 5 new vacation.

    Drezden  🇩🇪

    Frontend Developer
    https://bit.ly/2tVkBLK

    Software Architect
    https://bit.ly/2KI47jN

    The company is very successful since the beginning in 2014 and is growing fast. Its core business is an app that helps companies reach their employees better and comunicate more effectively.

    Трактор в Баварию  🇩🇪

    Evolvice Team is looking for Senior .NET Developer with relocation to our client to Bergkirchen (Germany, Bavaria).

    Project: Impelmenting further features and later migrate the software also to a more web-based solution.
    Product is a very famous CAD design program. It is nr. 2 in Germany. There are other employees from eastern Europe in this company.

    https://bit.ly/2MmEfHF

    Трактор в Мюнхен  🇩🇪

    Daxx is looking for an Embedded Linux Software Developer
    https://bit.ly/2Obf638

    Трактор в Краков  🇵🇱

    Intetics company is looking for Java developer to Krakow office. We fully ensure the process of relocation for you and your family. The project is a new platform for cross-media newsroom management targeted at medium-size and large publishing houses.

    https://bit.ly/2vsiFeD "

  farewell_message: "Bye! I'll miss you :("

  recruter_message_1: "Hi there, we can help you with hunting best talent in IT"
  recruter_message_2: https://lwlies.com/wp-content/uploads/2017/07/leon-the-professional-1108x0-c-default.jpg
  recruter_message_3: "Do you want to start"
  recruter_message_4: "Sounds good? (answer yes)"
  recruter_message_5: "Ok. Lets go to create your profile in 30 seconds"
  recruter_message_6: http://smoozy.io/company/sign_up
