default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bot_dev

test:
  <<: *default
  database: bot_test

production:
  <<: *default
  database: bot_prod


# production:
#   user_db:
#     url: 
#     database: my_primary_database
#     user: root
#     adapter: mysql
#   jobs_db:
#     database: my_primary_database
#     user: root_readonly
#     adapter: mysql
#     replica: true